import type { IRGraph } from './ir';

export const START_USER_INPUTS_PARAM = 'userInputs' as const;
export const START_GEN_PROVENANCE_PARAM = 'genProvenance' as const;

/**
 * Provenance of an AI-generated blueprint: how much "quantity-for-quality"
 * machinery produced it (multi-angle research, candidate consensus, complex-node
 * escalation). Stamped onto the Start node's params so the user can see, in the
 * inspector, what the blueprint went through. All fields optional — only the
 * phases that actually ran contribute. Counts are point-in-time at generation.
 */
export interface GenProvenance {
  /** Wall-clock ms when the blueprint was committed (caller injects Date.now()). */
  at?: number;
  /** Candidate blueprints generated by gen-consensus. */
  candidates?: number;
  /** Of those, how many parsed into a valid IRGraph. */
  candidatesValid?: number;
  /** Whether a judge merged multiple candidates into the final blueprint. */
  judgeMerged?: boolean;
  /** Research lenses actually run before generation. */
  researchLenses?: number;
  /** Of those, how many produced a usable conclusion. */
  researchUsable?: number;
  /** How many doubling rounds the research divergence loop took (1 = no escalation). */
  researchRounds?: number;
  /** Final measured research divergence (0..1). */
  researchDivergence?: number;
  /** How many generated agent nodes were auto-upgraded to consensus nodes. */
  upgradedNodes?: number;
}


const START_INPUT_PARAM_KEYS = [
  START_USER_INPUTS_PARAM,
  'inputs',
  'requirements',
  'requirement',
  'input',
  'prompt',
  'description',
] as const;

function textFromObject(value: Record<string, unknown>): string {
  const candidate =
    value.text ??
    value.content ??
    value.prompt ??
    value.answer ??
    value.value;
  if (candidate == null) return '';
  return textFromValue(candidate);
}

function textFromValue(value: unknown): string {
  if (value == null) return '';
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (typeof value === 'object' && !Array.isArray(value)) {
    return textFromObject(value as Record<string, unknown>);
  }
  return '';
}

function listFromValue(value: unknown): string[] {
  if (Array.isArray(value)) return value.map(textFromValue);
  return [textFromValue(value)];
}

function compactInputs(inputs: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const input of inputs) {
    const text = input.trim();
    if (!text) continue;
    // Case-insensitive dedup so that "Add a step" and "add a step" are
    // treated as the same entry. The first occurrence's casing is kept.
    const norm = text.toLowerCase();
    if (seen.has(norm)) continue;
    seen.add(norm);
    out.push(text);
  }
  return out;
}

/**
 * Read Start-node user inputs from the canonical `userInputs` field, while
 * tolerating older/AI-produced aliases such as `inputs` or `requirements`.
 */
export function readStartUserInputs(
  params: Record<string, unknown> | undefined,
): string[] {
  if (!params) return [];
  if (params[START_USER_INPUTS_PARAM] != null) {
    return compactInputs(listFromValue(params[START_USER_INPUTS_PARAM]));
  }
  for (const key of START_INPUT_PARAM_KEYS.slice(1)) {
    if (params[key] == null) continue;
    return compactInputs(listFromValue(params[key]));
  }
  return [];
}

function startParamsWithInputs(
  params: Record<string, unknown>,
  inputs: readonly string[],
): Record<string, unknown> {
  const next = { ...params };
  for (const key of START_INPUT_PARAM_KEYS) delete next[key];
  return { ...next, [START_USER_INPUTS_PARAM]: compactInputs(inputs) };
}

/** Append requirement/user-input entries to the first Start node in a graph. */
export function appendStartUserInputs(
  graph: IRGraph,
  additions: readonly string[],
): IRGraph {
  const nextAdditions = compactInputs(additions);
  if (nextAdditions.length === 0) return graph;

  const startNode = graph.nodes.find((node) => node.type === 'start');
  if (!startNode) return graph;

  const merged = compactInputs([
    ...readStartUserInputs(startNode.params),
    ...nextAdditions,
  ]);
  const current = readStartUserInputs(startNode.params);
  if (
    merged.length === current.length &&
    merged.every((value, index) => value === current[index])
  ) {
    return graph;
  }

  return {
    ...graph,
    nodes: graph.nodes.map((node) =>
      node.id === startNode.id
        ? {
            ...node,
            params: startParamsWithInputs(node.params ?? {}, merged),
          }
        : node,
    ),
  };
}

/** Read the AI-generation provenance stamped on the first Start node, if any. */
export function readGenerationProvenance(
  params: Record<string, unknown> | undefined,
): GenProvenance | null {
  const raw = params?.[START_GEN_PROVENANCE_PARAM];
  if (raw == null || typeof raw !== 'object' || Array.isArray(raw)) return null;
  return raw as GenProvenance;
}

/** Whether a provenance object carries any meaningful (non-empty) field. */
export function hasGenerationProvenance(prov: GenProvenance | null | undefined): boolean {
  if (!prov) return false;
  return Object.values(prov).some((v) => v != null);
}

/**
 * Stamp AI-generation provenance onto the first Start node's params (immutable,
 * mirrors {@link appendStartUserInputs}). No-op when the provenance is empty or
 * there is no Start node, so non-AI graphs are untouched.
 */
export function setGenerationProvenance(
  graph: IRGraph,
  provenance: GenProvenance,
): IRGraph {
  if (!hasGenerationProvenance(provenance)) return graph;
  const startNode = graph.nodes.find((node) => node.type === 'start');
  if (!startNode) return graph;
  return {
    ...graph,
    nodes: graph.nodes.map((node) =>
      node.id === startNode.id
        ? {
            ...node,
            params: {
              ...(node.params ?? {}),
              [START_GEN_PROVENANCE_PARAM]: provenance,
            },
          }
        : node,
    ),
  };
}
